# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alerting
  labels:
    app: alerting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alerting
  template:
    metadata:
      labels:
        app: alerting
    spec:
      containers:
        - name: alerting
          image: alerting:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: app-env-config
          volumeMounts:
            - name: env-file
              mountPath: /app/.env
              subPath: .env
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
      volumes:
        - name: env-file
          configMap:
            name: app-env-config
